const mongoose = require("mongoose");
var Schema = mongoose.Schema;

const assessorsSchema = new mongoose.Schema({
    Organization: {type: String},
    Organization2: {type: String},
    OrganizationLocation: {type: String},
    assessorsAlternateno: {type: String},
    assessorsDate: {type: String},
    assessorsEducation: {type: String},
    assessorsEmail: {type: String},
    assessorsFsmsqualified: {type: String},
    assessorsPhone: {type: String},
    assessorsSecondaryemail: {type: String},
    assessorsTraining: {type: String},
    batch: {type: String},
    designation: {type: String},
    domain: {type: Array},
    exposure: {type: Array},
    firstName: {type: String},
    fsmsCertificate: {type: String},
    org_Email: {type: String},
    org_Fullname: {type: String},
    organizationAddressline1: {type: String},
    organizationCity: {type: String},
    organizationCountry:{type: String},
    organizationDesignation: {type: String},
    organizationDesignation2: {type: String},
    organizationProductservice: {type: Array},
    organizationProductservice2: {type: Array},
    organizationState: {type: String},
    organizationZipcode: {type: String},
    report_Designation: {type: String},
    residentialAddressline: {type: String},
    residentialCity: {type: String},
    residentialCountry: {type: String},
    residentialState: {type: String},
    residentialZipcode: {type: String},
    skill: {type: String},
    zone: {type: String},
    experience:{type:String},
    created_at: { type: Date, default: Date.now },
    updated_at: { type: Date, default: Date.now },
    invite: { type: Boolean, default: false },
    status: { type: String, default: "active" },
    code1:{type:String},
    code2:{type:String},
    score:{type:String,default: "0" },
    rating:{type:String,default: "0" },
    rank:{type:String,default: "" },
});

module.exports = mongoose.model("assessors", assessorsSchema);